INTERACTIVE_MODELS_PATH: "./weights"
EXPS_PATH: "./experiments"

GRABCUT_PATH: "./datasets/GrabCut"
BERKELEY_PATH: "./datasets/Berkeley"
DAVIS_PATH: "./datasets/COCO_MVal"
SBD_PATH: "./datasets/SBD"
GRAB_PATH_TRAIN: "./datasets/GrabCut/train"
GRAB_PATH_VAL: "./datasets/GrabCut/val"
COCO_MVAL_PATH: "./datasets/COCO_MVal"
MASK_PATH_TRAIN: "./datasets/mask/train"
MASK_PATH_VAL: "./datasets/mask/val"

# You can download the weights for HRNet from the repository:
# https://github.com/HRNet/HRNet-Image-Classification
IMAGENET_PRETRAINED_MODELS:
  HRNETV2_W18: "./pretrained_models/hrnetv2_w18_imagenet_pretrained.pth"
  HRNETV2_W32: "./pretrained_models/hrnetv2_w32_imagenet_pretrained.pth"
  HRNETV2_W40: "./pretrained_models/hrnetv2_w40_imagenet_pretrained.pth"
  HRNETV2_W48: "./pretrained_models/hrnetv2_w48_imagenet_pretrained.pth"
